[build]
  base = "client/"
  publish = "client/build/"
  command = "yarn install && yarn build"

[context.production]
  environment = { REACT_APP_API_URL = "https://o2hlpsp9ac.execute-api.us-east-1.amazonaws.com/prod/api"}

[context.deploy-preview]
  environment = { REACT_APP_API_URL = "https://li0rnckwp5.execute-api.us-east-1.amazonaws.com/dev/api"}