[build]
  command = "yarn --cwd \"./server\" && yarn --cwd \"./client\" install && yarn build" # the command you run to build this file
  functions = "./server/.serverless" # netlify-lambda builds to this folder AND Netlify reads functions from here