Parameters:
  StageParam:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Join ["", ["salty-solutions-", Ref: StageParam]]
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: N
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
Outputs:
  MainTableName:
    Value: !Ref MainTable
    Export:
      Name: MainTableName
  MainTableArn:
    Value: !GetAtt MainTable.Arn
    Export:
      Name: MainTableArn
