Parameters:
  StageParam:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["", ["dead-letter-", Ref: StageParam]]
      MessageRetentionPeriod: 1209600 # 14 days

  ForecastPreloaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["", ["forecast-preloader-", Ref: StageParam]]
      VisibilityTimeout: 120
      MessageRetentionPeriod: 43200 # 12 hours
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 3
  TidePreloaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["", ["tide-preloader-", Ref: StageParam]]
      VisibilityTimeout: 120
      MessageRetentionPeriod: 43200 # 12 hours
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 3
  WindFinderPreloaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["", ["windfinder-preloader-", Ref: StageParam]]
      VisibilityTimeout: 120
      MessageRetentionPeriod: 43200 # 12 hours
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 3
  UsgsPreloaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["", ["usgs-preloader-", Ref: StageParam]]
      VisibilityTimeout: 120
      MessageRetentionPeriod: 43200 # 12 hours
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 3
Outputs:
  ForecastPreloaderQueueUrl:
    Value: !Ref ForecastPreloaderQueue
    Export:
      Name: !Join ["-", [ForecastPreloaderQueueUrl, Ref: StageParam]]
  ForecastPreloaderQueueArn:
    Value: !GetAtt ForecastPreloaderQueue.Arn
    Export:
      Name: !Join ["-", [ForecastPreloaderQueueArn, Ref: StageParam]]
  TidePreloaderQueueUrl:
    Value: !Ref TidePreloaderQueue
    Export:
      Name: !Join ["-", [TidePreloaderQueueUrl, Ref: StageParam]]
  TidePreloaderQueueArn:
    Value: !GetAtt TidePreloaderQueue.Arn
    Export:
      Name: !Join ["-", [TidePreloaderQueueArn, Ref: StageParam]]
  WindFinderPreloaderQueueUrl:
    Value: !Ref WindFinderPreloaderQueue
    Export:
      Name: !Join ["-", [WindFinderPreloaderQueueUrl, Ref: StageParam]]
  WindFinderPreloaderQueueArn:
    Value: !GetAtt WindFinderPreloaderQueue.Arn
    Export:
      Name: !Join ["-", [WindFinderPreloaderQueueArn, Ref: StageParam]]
  UsgsPreloaderQueueUrl:
    Value: !Ref UsgsPreloaderQueue
    Export:
      Name: !Join ["-", [UsgsPreloaderQueueUrl, Ref: StageParam]]
  UsgsPreloaderQueueArn:
    Value: !GetAtt UsgsPreloaderQueue.Arn
    Export:
      Name: !Join ["-", [UsgsPreloaderQueueArn, Ref: StageParam]]
