service:
  name: fishing-app

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  timeout: 500
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTimeToLive
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:SendMessageBatch
      Resource: "arn:aws:sqs:us-east-1:*:*"
  environment:
    SERVERLESS_STAGE: ${self:provider.stage}
    ROLLBAR_KEY: ${env:ROLLBAR_KEY}

functions:
  graphql:
    handler: ./src/server.graphql
    events:
      - http:
          cors: true
          method: any
          path: api

  preload-forecast-producer:
    handler: src/preloaders/producers.forecast
    events:
      - schedule:
          name: ForecastPreloader-${self:provider.stage}
          # enabled: ${self:custom.schedule_enabled.${self:provider.stage}, false}
          # rate: rate(3 hours)
          enabled: true
          rate: rate(1 minute)
    environment:
      QUEUE_URL:
        Ref: ForecastPreloaderQueue
  # preload-forecast-consumer:
  #   handler: src/preloaders/consumers.forecast
  #   events:
  #     - sqs:
  #         arn:
  #           Fn::GetAtt:
  #             - ForecastPreloaderQueue
  #             - Arn

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: salty-solutions-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    ForecastPreloaderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: forecast-preloader-${self:provider.stage}

custom:
  serverless-offline:
    port: 4000
  schedule_enabled:
    prod: true
    dev: false
