service:
  name: fishing-app

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless

functions:
  graphql:    
    handler: ./src/server.graphql
    events:      
      - http:
          cors: true
          method: any
          path: api

custom:
  serverless-offline:
    port: 4000