service:
  name: fishing-app

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

functions:
  graphql:
    handler: ./src/server.graphql
    events:
      - http:
          cors: true
          method: any
          path: api
    environment:
      SERVERLESS_STAGE: ${self:provider.stage}
      ROLLBAR_KEY: ${env:ROLLBAR_KEY}
  # preload-forecast:
  #   handler: src/preloaders.forecast
  #   events:
  #     - schedule: rate(1 hours)

resources:
  Resources:
    mainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: salty-solutions-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE

  custom:
  serverless-offline:
    port: 4000
