name: Deploy Application
on:
  push:
    branches:
      - master
jobs:
  backend:
    name: "Deploy backend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: cd server
      - run: pwd
      - run: npm install
        env:
          ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
