name: Deploy Application
on:
  push:
    branches:
      - master
jobs:
  backend:
    name: "Deploy backend"
    runs-on: ubuntu-latest
    env:
      ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SERVERLESS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_SERVERLESS }}
      STAGE: prod
      AWS_DEFAULT_REGION: "us-east-1"
      NPM_GITHUB_PACKAGE_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn cf:update-db && yarn cf:update-queue
        working-directory: ./server
      - run: ./node_modules/.bin/sls deploy --stage ${{ env.STAGE }}
        working-directory: ./server
